In [2]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
from sklearn.linear_model import Perceptron

In [5]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
standardized = StandardScaler()

standardized_X_test = standardized.fit_transform(X_test)
standardized_X_train = standardized.fit_transform(X_train)

In [8]:
standardized_X_test[0:10,]

array([[-0.83139839,  1.01063225, -1.13340934, -0.69116352],
       [ 2.00560085, -0.47351301,  1.45122345,  1.10586163],
       [ 0.11426802, -0.68553377,  0.87686061,  1.10586163],
       [-1.06781499, -0.04947151, -1.24828191, -1.10586163],
       [-0.71319008,  1.64669451, -0.96110049, -0.96762892],
       [ 2.59664235,  1.64669451,  1.6235323 ,  1.24409433],
       [ 0.46889293, -0.89755452,  1.16404203,  0.41469811],
       [ 0.82351783,  0.37457   ,  0.99173317,  1.65879244],
       [-0.71319008, -1.10957527, -0.32930136,  0.        ],
       [-0.24035688, -1.32159602,  0.07275263, -0.1382327 ]])

In [9]:
perceptron = Perceptron(max_iter = 50, eta0 = 0.15, tol = 1e-3, random_state = 15)
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
           fit_intercept=True, max_iter=50, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=15, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [10]:
y_pred = perceptron.predict(standardized_X_test)

In [11]:
print(y_test)

[0 2 2 0 0 2 2 2 1 1 1 0 0 0 0 1 1 1 1 1 1 2 1 0 0 2 2 0 1 0]


In [12]:
print(y_pred)

[0 2 2 0 0 2 2 2 1 1 1 0 0 0 0 1 2 2 1 2 1 2 1 0 1 2 2 0 1 0]


In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.89      0.73      0.80        11
           2       0.73      1.00      0.84         8

    accuracy                           0.87        30
   macro avg       0.87      0.88      0.86        30
weighted avg       0.89      0.87      0.87        30

